# Generated by Django 2.0.1 on 2018-07-05 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180705_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesprofile',
            name='sales_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
