# Generated by Django 2.0.1 on 2018-07-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180706_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinformation',
            name='activation',
            field=models.CharField(default='', max_length=255),
        ),
    ]
