# Generated by Django 2.0.1 on 2018-07-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180707_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinformation',
            name='activation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deshbroad.activation_code'),
        ),
    ]
