# Generated by Django 2.0.1 on 2018-07-09 15:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, upload_to=accounts.models.image_upload),
        ),
    ]
