# Generated by Django 2.0.1 on 2018-08-06 16:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180806_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', upload_to=accounts.models.image_upload),
        ),
    ]
