# Generated by Django 2.0.1 on 2018-08-10 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_message_notification_message_notification_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_notification_read',
            name='user_Message',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
