# Generated by Django 2.0.1 on 2018-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180811_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinformation',
            name='day',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='saleinformation',
            name='month',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='saleinformation',
            name='year',
            field=models.CharField(default='', max_length=20),
        ),
    ]
