# Generated by Django 2.0.1 on 2018-08-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180826_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_per_rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
