# Generated by Django 2.0.1 on 2018-09-02 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_technicalsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_notification',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
