# Generated by Django 2.0.1 on 2018-10-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_message_notification_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='districtBangladesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OfferPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_offer', models.ImageField(upload_to='')),
                ('image_details', models.ImageField(upload_to='')),
            ],
        ),
    ]
