# Generated by Django 2.0.1 on 2018-10-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_districtbangladesh_offerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankListBangladesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='district_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.districtBangladesh'),
        ),
        migrations.AlterField(
            model_name='districtbangladesh',
            name='district_name',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankListBangladesh'),
        ),
    ]
