# Generated by Django 2.0.1 on 2018-10-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20181009_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='offerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='district_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.districtBangladesh'),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankListBangladesh'),
        ),
        migrations.AddField(
            model_name='offerpage',
            name='offer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.offerType'),
        ),
    ]
