# Generated by Django 2.0.1 on 2018-07-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activation_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('sales_code', models.CharField(max_length=200)),
                ('customer_code', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('product_type', models.CharField(max_length=255)),
                ('check', models.BooleanField()),
            ],
        ),
    ]
