# Generated by Django 2.0.1 on 2018-09-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deshbroad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation_code',
            name='active_check',
            field=models.BooleanField(default=False),
        ),
    ]
