# Generated by Django 2.0.1 on 2018-12-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_auto_20181011_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatwayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_activate_paind', models.IntegerField()),
                ('current_paid', models.IntegerField()),
                ('unit_rate', models.FloatField()),
                ('total_taka', models.FloatField()),
                ('massage', models.CharField(blank=True, max_length=255)),
                ('salesUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SaleInformation')),
            ],
        ),
    ]
